# Generated by Django 5.0.7 on 2026-07-03 15:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('challenge_date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'daily_challenge',
                'ordering': ['-challenge_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('round_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('system_design', 'System Design')], max_length=20)),
                ('readiness_score', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('resume_file_path', models.CharField(blank=True, default='', max_length=500)),
                ('resume_data', models.JSONField(blank=True, default=dict)),
                ('enhanced_resume', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_seeker_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('user_answer', models.TextField(blank=True, default='')),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('model_answer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.interviewsession')),
            ],
            options={
                'db_table': 'interview_answer',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('cover_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='api.jobseekeraccount'),
        ),
        migrations.CreateModel(
            name='DevPulseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('level', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Principal', 'Principal'), ('Legend', 'Legend')], default='Intern', max_length=20)),
                ('total_xp', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('career_health_score', models.IntegerField(default=0)),
                ('target_role', models.CharField(blank=True, max_length=150, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devpulse_profile', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'devpulse_profile',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unique_cert_id', models.CharField(max_length=30, unique=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'certificate',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('skill', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('done', 'Done')], default='waiting', max_length=10)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_rooms_as_p1', to='api.jobseekeraccount')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_rooms_as_p2', to='api.jobseekeraccount')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_wins', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'battle_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('status_updated', 'Status Updated'), ('new_match', 'New Match'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tech_stack', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('ai_bullets', models.JSONField(default=list)),
                ('skills_extracted', models.JSONField(default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'quiz_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('template_id', models.CharField(default='modern', max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('ats_report', models.JSONField(blank=True, null=True)),
                ('exported_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'resume_draft',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('xp_amount', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'xp_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=list)),
                ('score', models.IntegerField()),
                ('time_taken_seconds', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.battleroom')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'battle_submission',
                'ordering': ['submitted_at'],
                'unique_together': {('room', 'seeker')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=60)),
                ('badge_icon', models.CharField(max_length=10)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'user_badge',
                'ordering': ['-earned_at'],
                'unique_together': {('seeker', 'badge_name')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('is_self_marked', models.BooleanField(default=False)),
                ('xp_contribution', models.IntegerField(default=0)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'user_skill',
                'unique_together': {('seeker', 'skill_name')},
            },
        ),
    ]
